# mapping_config.yaml

# Mapping configuration for Salesforce Data Cloud objects.
# Each section defines mappings for a specific object, mapping CRM or other source fields to Salesforce fields.

Account:
  source_account_name: Name
  source_account_id: External_Id__c
  source_billing_address: BillingAddress
  source_phone: Phone
  source_website: Website

Contact:
  source_contact_name: Name
  source_email: Email
  source_phone: Phone
  source_mobile: MobilePhone
  source_address: MailingAddress
  source_account_id: AccountId

Lead:
  source_lead_name: Name
  source_company: Company
  source_email: Email
  source_phone: Phone
  source_status: Status
  source_lead_source: LeadSource

Opportunity:
  source_opportunity_name: Name
  source_close_date: CloseDate
  source_stage: StageName
  source_account_id: AccountId
  source_amount: Amount

Custom_Object__c:
  source_field1: Custom_Field1__c
  source_field2: Custom_Field2__c
  source_field3: Custom_Field3__c
