# This configuration file provides field mappings for different Salesforce objects.
# Each Salesforce object has specific mappings for the fields coming from the source data.

# Mapping for Salesforce Account object
Account:
  source_account_name: Name
  source_account_id: External_Id__c
  source_billing_address: BillingAddress
  source_phone: Phone
  source_website: Website

# Mapping for Salesforce Contact object
Contact:
  source_contact_name: Name
  source_email: Email
  source_phone: Phone
  source_mobile: MobilePhone
  source_address: MailingAddress
  source_account_id: AccountId

# Mapping for Salesforce Lead object
Lead:
  source_lead_name: Name
  source_company: Company
  source_email: Email
  source_phone: Phone
  source_status: Status
  source_lead_source: LeadSource

# Mapping for Salesforce Opportunity object
Opportunity:
  source_opportunity_name: Name
  source_close_date: CloseDate
  source_stage: StageName
  source_account_id: AccountId
  source_amount: Amount

# Example custom object mapping (if applicable)
Custom_Object__c:
  source_field1: Custom_Field1__c
  source_field2: Custom_Field2__c
  source_field3: Custom_Field3__c
